[package]
name = "mithril-common"
version = "0.2.95"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[[bench]]
name = "digester"
harness = false

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
bech32 = "0.9.1"
blake2 = "0.10.6"
chrono = { version = "0.4.26", features = ["serde"] }
digest = "0.10.7"
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
fixed = "1.23.1"
glob = "0.3.1"
hex = "0.4.3"
http = "0.2.9"
jsonschema = "0.17.1"
kes-summed-ed25519 = { version = "0.2.0", features = [
    "serde_enabled",
    "sk_clone_enabled",
] }
mockall = "0.11.4"
nom = "7.1.3"
rand-chacha-dalek-compat = { package = "rand_chacha", version = "0.2" }
rand_chacha = "0.3.1"
rand_core = "0.6.4"
rayon = "1.7.0"
semver = "1.0.18"
serde = { version = "1.0.183", features = ["derive"] }
serde_bytes = "0.11.12"
serde_cbor = "0.11.2"
serde_json = "1.0.105"
serde_with = "3.2.0"
serde_yaml = "0.9.25"
sha2 = "0.10.7"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_debug",
] }
slog-scope = "4.4.0"
sqlite = { version = "0.31.0", features = ["bundled"] }
strum = "0.25.0"
strum_macros = "0.25.2"
thiserror = "1.0.47"
tokio = { version = "1.32.0", features = ["full"] }
typetag = "0.2.13"
walkdir = "2.3.3"
warp = "0.3.5"

[target.'cfg(not(windows))'.dependencies]
# non-windows: use default rug backend
mithril-stm = { path = "../mithril-stm" }

[target.'cfg(windows)'.dependencies]
# Windows doesn't support rug backend, fallback to num-integer
mithril-stm = { path = "../mithril-stm", default-features = false, features = [
    "num-integer-backend",
] }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports", "async_tokio"] }
slog-async = "2.7.0"
slog-scope = "4.4.0"
slog-term = "2.9.0"

[build-dependencies]
glob = "0.3.1"
semver = "1.0.18"
serde_json = "1.0.105"
serde_yaml = "0.9.25"

[features]
default = []
portable = [
    "mithril-stm/portable",
] # portable feature avoids SIGILL crashes on CPUs not supporting Intel ADX instruction set when built on CPUs that support it
allow_skip_signer_certification = []
