[package]
name = "mithril-aggregator"
version = "0.3.72"
description = "A Mithril Aggregator server"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.73"
chrono = { version = "0.4.26", features = ["serde"] }
clap = { version = "4.3.22", features = ["derive", "env", "cargo"] }
cloud-storage = "0.11.1"
config = "0.13.3"
flate2 = "1.0.27"
hex = "0.4.3"
mithril-common = { path = "../mithril-common" }
openssl = { version = "0.10.56", features = ["vendored"], optional = true }
openssl-probe = { version = "0.1.5", optional = true }
reqwest = { version = "0.11.18", features = ["json"] }
semver = "1.0.18"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.105"
serde_yaml = "0.9.25"
sha2 = "0.10.7"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_debug",
] }
slog-async = "2.7.0"
slog-bunyan = "2.4.0"
slog-scope = "4.4.0"
sqlite = { version = "0.31.0", features = ["bundled"] }
tar = "0.4.40"
thiserror = "1.0.47"
tokio = { version = "1.32.0", features = ["full"] }
tokio-util = { version = "0.7.8", features = ["codec"] }
typetag = "0.2.13"
uuid = { version = "1.4.1", features = ["v4", "fast-rng", "macro-diagnostics"] }
warp = "0.3.5"

[dev-dependencies]
httpmock = "0.6.8"
mithril-common = { path = "../mithril-common", features = [
    "allow_skip_signer_certification",
] }
mockall = "0.11.4"
slog-term = "2.9.0"
tempfile = "3.7.1"

[features]
portable = [
    "mithril-common/portable",
] # portable feature avoids SIGILL crashes on CPUs not supporting Intel ADX instruction set when built on CPUs that support it
bundle_openssl = ["dep:openssl", "dep:openssl-probe"]
